# ---------- Base image ----------
FROM python:3.10-slim

# ---------- System deps ----------
RUN apt-get update

# ---------- Workdir ----------
WORKDIR /app

# ---------- Copy application code ----------
COPY inference/* .
    
# ---------- Install Python deps ----------
RUN pip install --no-cache-dir -r requirements.txt

# ---------- Expose port ----------
EXPOSE 8000

# ---------- Run server ----------
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
